[package]
name = "myip"
version = "0.1.0"
authors = ["Kevin Gimbel <hallo@kevingimbel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"